language: java
jdk:
  - oraclejdk8
#trusty-deconfiança somente para dizer ao travis que a versão do java informada é confiável
dist: trusty
#pode ocorrer de dar falha ao tentar executar o mvnw, para isso vamos acrescentar o comando abaixo
#dando permissão de execução
before_install:
  - chmod +x mvnw
